name: PR Source Code Check

on:
  workflow_dispatch:
  push:

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: '22'
          cache: 'yarn'
      - run: yarn
      - run: yarn lint

  tsc:
    name: Run Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: '22'
          cache: 'yarn'
      - run: yarn
      - run: yarn tsc

  prettier:
    name: Run Prettier Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: '22'
          cache: 'yarn'
      - run: yarn
      - run: yarn format
